# Generated by Django 6.0.5 on 2026-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع التقرير')),
                ('content', models.JSONField(verbose_name='محتوى التقرير')),
                ('period_start', models.DateField(verbose_name='تاريخ بداية الفترة')),
                ('period_end', models.DateField(verbose_name='تاريخ نهاية الفترة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'تقارير',
                'ordering': ['-created_at'],
            },
        ),
    ]
