# Generated by Django 6.0.5 on 2026-08-16 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.JSONField(verbose_name='Report content'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_end',
            field=models.DateField(verbose_name='Period end date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_start',
            field=models.DateField(verbose_name='Period start date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20, verbose_name='Report type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Report title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
