# Generated by Django 6.0.5 on 2026-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('notification_type', models.CharField(choices=[('complaint_reply', 'رد على شكوى'), ('aid_pickup', 'موعد استلام مساعدة')], max_length=20, verbose_name='نوع الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم قراءته')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('read_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='وقت القراءة')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
