# Generated by Django 6.0.5 on 2026-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('complaint_reply', 'رد على شكوى'), ('aid_pickup', 'موعد استلام مساعدة'), ('manual', 'إشعار يدوي')], max_length=20, verbose_name='نوع الإشعار'),
        ),
    ]
