import LoaderWrapper from "./Component/Section/LoaderWrapper";
import ScrollButton from "./Component/UI/ScrollButton";
import ServiceWorkerRegister from "./Component/ServiceWorkerRegister";
import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import TopBar from "../app/Component/layout/Topbar";


const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={outfit.className}>
      <body className=" overflow-y-scroll scrollbar-custom">
      <ServiceWorkerRegister/>
        <LoaderWrapper>
          <div className="md:px-12.5 px-3  flex flex-col  min-h-screen  py-2">
            <TopBar/>
            {children}
            <ScrollButton />
          </div>
        </LoaderWrapper>
      </body>
    </html>
  );
}
