# Generated by Django 6.0.5 on 2026-05-23 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(40, message='الطول يجب أن يكون أكبر من 40'), django.core.validators.MaxValueValidator(200, message='الطول يجب أن يكون أقل من 200')], verbose_name='الطول (سم)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(2, message='الوزن يجب أن يكون أكبر من 2'), django.core.validators.MaxValueValidator(120, message='الوزن يجب أن يكون أقل من 120')], verbose_name='الوزن (كجم)')),
                ('BMI', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='مؤشر كتلة الجسم')),
                ('nutrition_status', models.CharField(choices=[('severe_malnutrition', 'سوء تغذية شديد'), ('moderate_malnutrition', 'سوء تغذية متوسط')], editable=False, max_length=25, verbose_name='الحالة الغذائية')),
            ],
            options={
                'verbose_name': 'مستفيد',
                'verbose_name_plural': 'المستفيدين',
            },
        ),
    ]
