# Generated by Django 6.0.5 on 2026-08-14 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(verbose_name='birth of date'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(40, message='الطول يجب أن يكون أكبر من 40'), django.core.validators.MaxValueValidator(200, message='الطول يجب أن يكون أقل من 200')], verbose_name='tall(cm)'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(2, message='الوزن يجب أن يكون أكبر من 2'), django.core.validators.MaxValueValidator(120, message='الوزن يجب أن يكون أقل من 120')], verbose_name='weight (kg)'),
        ),
    ]
