# Generated by Django 6.0.5 on 2026-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_alter_beneficiary_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='face_encoding',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Face encoding'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='beneficiaries/profile_images/', verbose_name='Beneficiary profile photo'),
        ),
    ]
