# Generated by Django 6.0.5 on 2026-08-16 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_beneficiary_face_encoding_beneficiary_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='BMI',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Body mass index (BMI)'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(40, message='Height must be at least 40 cm.'), django.core.validators.MaxValueValidator(200, message='Height must not exceed 200 cm.')], verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nutrition_status',
            field=models.CharField(choices=[('severe_malnutrition', 'Severe malnutrition'), ('moderate_malnutrition', 'Moderate malnutrition')], editable=False, max_length=25, verbose_name='Nutrition status'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(2, message='Weight must be at least 2 kg.'), django.core.validators.MaxValueValidator(120, message='Weight must not exceed 120 kg.')], verbose_name='Weight (kg)'),
        ),
    ]
