# Generated by Django 6.0.5 on 2026-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجه'), ('resolved', 'تم الحل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الشكوى')),
                ('description', models.TextField(verbose_name='وصف الشكوى')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('replies_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الرد')),
            ],
            options={
                'verbose_name': 'شكوى',
                'verbose_name_plural': 'الشكاوى',
                'ordering': ['-created_at'],
            },
        ),
    ]
