# Generated by Django 6.0.5 on 2026-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الشكوى'),
        ),
    ]
