# Generated by Django 6.0.5 on 2026-08-16 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='Complaint description'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Replied by'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='replies_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Replied at'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Complaint title'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
