# Generated by Django 6.0.5 on 2026-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('confirmed_by_beneficiary', models.BooleanField(default=False, verbose_name='تم التاكيد ان المستلم استلم المساعده')),
            ],
            options={
                'verbose_name': 'سجل تسليم المساعدة',
                'verbose_name_plural': 'سجلات تسليم المساعدة',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='AidSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField(verbose_name='تاريخ استلام المساعدة')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الاستلام'), ('missed', 'لم يستلم'), ('received', 'تم الاستلام')], default='pending', max_length=20, verbose_name='حالة المساعدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'جدول المساعدة',
                'verbose_name_plural': 'جداول المساعدة',
                'ordering': ['-schedule_date'],
            },
        ),
    ]
