# Generated by Django 6.0.5 on 2026-05-23 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aid', '0001_initial'),
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidhistory',
            name='delivered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivered_aids_histories', to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي سلم المساعده'),
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_schedules', to='beneficiaries.beneficiary', verbose_name='المستفيد'),
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_aid_schedules', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المنشئ'),
        ),
        migrations.AddField(
            model_name='aidhistory',
            name='aid_Schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aid_history', to='aid.aidschedule', verbose_name='جدول المساعدة'),
        ),
    ]
