# Generated by Django 6.0.5 on 2026-08-16 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_initial'),
        ('beneficiaries', '0004_beneficiary_face_encoding_beneficiary_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidhistory',
            options={'ordering': ['-delivery_date'], 'verbose_name': 'Aid delivery history', 'verbose_name_plural': 'Aid delivery histories'},
        ),
        migrations.AlterModelOptions(
            name='aidschedule',
            options={'ordering': ['-schedule_date'], 'verbose_name': 'Aid schedule', 'verbose_name_plural': 'Aid schedules'},
        ),
        migrations.AddField(
            model_name='aidhistory',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Face match score'),
        ),
        migrations.AddField(
            model_name='aidhistory',
            name='face_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Face verified'),
        ),
        migrations.AlterField(
            model_name='aidhistory',
            name='aid_Schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aid_history', to='aid.aidschedule', verbose_name='Aid schedule'),
        ),
        migrations.AlterField(
            model_name='aidhistory',
            name='confirmed_by_beneficiary',
            field=models.BooleanField(default=False, verbose_name='Confirmed by beneficiary'),
        ),
        migrations.AlterField(
            model_name='aidhistory',
            name='delivered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivered_aids_histories', to=settings.AUTH_USER_MODEL, verbose_name='Delivered by'),
        ),
        migrations.AlterField(
            model_name='aidhistory',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='aidschedule',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_schedules', to='beneficiaries.beneficiary', verbose_name='Beneficiary'),
        ),
        migrations.AlterField(
            model_name='aidschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='aidschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_aid_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='aidschedule',
            name='schedule_date',
            field=models.DateTimeField(verbose_name='Aid pickup date'),
        ),
        migrations.AlterField(
            model_name='aidschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('missed', 'Missed'), ('received', 'Received')], default='pending', max_length=20, verbose_name='Aid status'),
        ),
        migrations.AlterField(
            model_name='aidschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
