# Generated by Django 6.0.5 on 2026-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المقال')),
                ('content', models.TextField(verbose_name='محتوى المقال')),
                ('category', models.CharField(choices=[('nutrition', 'تغذية'), ('health', 'صحة عامة'), ('children', 'تغذية الأطفال'), ('pregnancy', 'تغذية الحامل'), ('chronic_diseases', 'الأمراض المزمنة'), ('awareness', 'توعية')], max_length=20, verbose_name='فئة المقال')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
