# Generated by Django 6.0.5 on 2026-08-16 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Backup', 'verbose_name_plural': 'Backups'},
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='File path'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name='File size (bytes)'),
        ),
    ]
