# Generated by Django 6.0.5 on 2026-05-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_manager_constraint',
        ),
    ]
