# Generated by Django 6.0.5 on 2026-08-14 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_unique_manager_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم الوطني يجب أن يتكون من 11 رقم فقط', regex='^[0-9]{11}$')], verbose_name='national id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message=' رقم الهاتف يجب أن يبدا بالصفر وفيه تسغ ارقام ', regex='^09[0-9]{8}$')], verbose_name='phone number'),
        ),
    ]
