# Generated by Django 6.0.5 on 2026-08-16 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='The national ID must contain exactly 11 digits.', regex='^[0-9]{11}$')], verbose_name='national id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The phone number must start with 09 and contain exactly 10 digits.', regex='^09[0-9]{8}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('beneficiary', 'Beneficiary'), ('registration', 'Registration'), ('awareness', 'Awareness'), ('helpdesk', 'Help desk'), ('manager', 'Manager')], default='beneficiary', max_length=20, verbose_name='Role'),
        ),
    ]
