"""
Django settings for health_center project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
# هلا انا ضفته مشان حدد من خلاله مدخ بقاء التوكنز

from pathlib import Path
# من اجل التعامل مع مسارات المجلدات

import os
import dj_database_url

from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# مشان يوصل عمكان المشروع الرئيسي يللي هو اب اب هاد الملف


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

DEBUG = config(
    'DEBUG',
    default=False,
    cast=bool,
)
# هاد رقم سري بساعد كتوقيع من اجل الثقه بالتوكنز والكوكيز

# SECURITY WARNING: don't run with debug turned on in production!
# وضع التطوير وقت انشره لازم اعملا false لان ممكن للي بيفتح
# يشوف مسارات البينات وتفاصيل عن قاعده البيانات


ALLOWED_HOSTS = [
    "health-center-api-t6qh.onrender.com",
    "127.0.0.1",
    "localhost",
    ".ngrok-free.app",
    ".ngrok-free.dev",
]


RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME"
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    # الهوستات يللي مسمحلها تشغل موقعي


# ORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]


CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]

# (يعني هي اسم الدومين تبع موقعي)


# Application definition

INSTALLED_APPS = [
    'django_filters',
    "corsheaders",
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'backups',
    'reports',
    'aid',
    'notifications',
    # لو ما ضفته ما رح يعرف مشروعي انه عندي هال ابب لازم يشغله
    'complaints',
    # لو ما ضفته ما رح يعرف مشروعي انه عندي هال ابب لازم يشغله
    'articles',
    'beneficiaries',
    # لو ما ضفته ما رح يعرف مشروعي انه عندي هال ابب لازم يشغله
    'users',
    # لو ما ضفته ما رح يعرف مشروعي انه عندي هال ابب لازم يشغله
    'health_center.apps.HealthCenterAdminConfig',
    # هي واجهة الادمن بدخل وبدير جداول الداتا بيز بدون برمجخ
    # /admin/ بتصير بعد امر انشاء سوبر يوزر
    'django.contrib.auth',
    # من اجل التعامل مع المودلز يعني مع الداتا بيز
    # منح صلاحيات ادمن و سجل العمليات حذف او شي من هيك امور
    'django.contrib.contenttypes',
    # يعني هو الذي يعمل فهرس لكل Model موجود في المشروع
    'django.contrib.sessions',
    # هاد مشان يحفظ بيانات تسجيل الدخول
    'django.contrib.messages',
    # للرسائل المؤفته لن اعتمد عليها كثيرا لاني باك اند
    'django.contrib.staticfiles',
    # مشان ال CSS والصور الخاصه بصفحه الادمن
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # حمايه من الهجمات يضيف حمايه امنيه https
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # بشوف اذا مسجل المستخدم دخوله قبل
    'django.middleware.common.CommonMiddleware',
    # بصلح الروابط يعني بضيف / باخر الروابط
    'django.middleware.csrf.CsrfViewMiddleware',
    # من اجل الحمايه من هجمات csrf
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # هون بيربط كل طلب بالمستخدم المسجل دخوله
    'django.contrib.messages.middleware.MessageMiddleware',
    # يدير نظام الرسائل المؤقته الخاصه بال app messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# للحمايه من هجمات clickjacking


ROOT_URLCONF = 'health_center.urls'
# يعني وقت يوصل التنفيذ لهون بقله روح عال urls.py


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # محرك خاص لملفات html
        'DIRS': [BASE_DIR / 'templates'],
        # مجلدات اضافيه تبحث عن ملفات html
        'APP_DIRS': True,
        # ابحث عن مجلد templates داخل كل app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'health_center.wsgi.application'

# هون مشان وقت الرفع عسيرفر حقيقي بروح عال wsgi
# وبفعل التابع get الموجود بهداك الملف ضمن يساوي application


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config(
                'DB_HOST',
                default='localhost',
            ),
            'PORT': config(
                'DB_PORT',
                default='3306',
            ),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    # سيقارن هل كلمه السر مشابهة للاسم ويرفضها اذا كانت كذلك
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    # اقل عدد احرف يعني الافتراضي 8 احرف
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    # لا تكون كلمه المرور شائعه متل 123456
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
    # لا تكون ارقام فقط
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Amman'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Face verification

FACE_MODELS_DIR = BASE_DIR / 'face_models'

FACE_DETECTOR_MODEL = (
    FACE_MODELS_DIR
    / 'face_detection_yunet_2023mar.onnx'
)

FACE_RECOGNIZER_MODEL = (
    FACE_MODELS_DIR
    / 'face_recognition_sface_2021dec.onnx'
)

FACE_DETECTION_THRESHOLD = 0.6
FACE_MATCH_THRESHOLD = 0.363

FACE_MAX_UPLOAD_SIZE = 5 * 1024 * 1024
FACE_MAX_IMAGE_PIXELS = 20_000_000

FACE_PHOTO_MAX_SIZE = (500, 500)
FACE_PHOTO_QUALITY = 85

AID_FACE_VERIFICATION_TOKEN_MAX_AGE = 300


USE_CLOUDINARY_STORAGE = bool(
    os.environ.get(
        "CLOUDINARY_URL",
        "",
    ).strip()
)


STORAGES = {
    "default": {
        "BACKEND": (
            "health_center.storage.CloudinaryMediaStorage"
            if USE_CLOUDINARY_STORAGE
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


AUTH_USER_MODEL = 'users.CustomUser'
# هون يعني بروح عهالجدول وهو ميبني المايجريشنز
# بدل ميبني شي افتراضي


# ============================================================
# Django REST Framework Configuration
# ============================================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        (
            'rest_framework_simplejwt.authentication.'
            'JWTAuthentication'
        ),
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        # فلتره بالتطابق التام
        'rest_framework.filters.SearchFilter',
        # بحث نصي بحقول متعدده
        'rest_framework.filters.OrderingFilter',
        # ترتيب ديناميكي حسب اي حقل
    ],
    'DEFAULT_PAGINATION_CLASS': (
        'rest_framework.pagination.PageNumberPagination'
    ),
    'PAGE_SIZE': 20,
    # هون يعني كل صفحه 20 مستخدم بدل 200 مستخدم مع بعض
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    # كل مره باستخدم الريفريش لجدد الاكسيس
    'BLACKLIST_AFTER_ROTATION': True,
    # بعد الروتيشن بيحظر القديم وبيحطه بالبلاك ليست
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': (
        'rest_framework_simplejwt.tokens.AccessToken',
    ),
}


PASSWORD_RESET_TIMEOUT = 3600


# القسم الخاص بالايميل قيد التطوير
# Gmail SMTP configuration

EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
)

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

EMAIL_TIMEOUT = 20

DEFAULT_FROM_EMAIL = (
    'Health Nutritional Support Center '
    '<nabdhealthcenter@gmail.com>'
)


CSRF_TRUSTED_ORIGINS = [
    "https://health-center-api-t6qh.onrender.com",
    "https://*.ngrok-free.app",
    "https://*.ngrok-free.dev",
]


if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{RENDER_EXTERNAL_HOSTNAME}"
    )